Add Spanish translation in coco_1_coding_environment.md
CodeToCommunicate/CoCoLessons pull request #26
Opened 2022-01-18 17:58 UTC by aguspesce

2022-01-18 18:00 UTC, aguspesce commented
@isamarcortes and @santisoler try to check my translation

2022-01-18 20:31 UTC, santisoler requested changes
Gracias @aguspesce por las traducciones. Dejé abajo algunas modificaciones, especialmente haciendo uso del tuteo.
Corregí algunos errores de ortografía menores, y cambién algunas traducciones específicas como _carpeta de usuario_, por ejemplo.

En el caso de este archivo en particular, me quedé pensando si no sería mejor tener toda una sección en inglés y otra en español. Ya que aquí no hay celdas que necesitemos copiar y pegar, fácilmente podríamos tener un texto para cada uno de los idiomas, lo cual hace más fácil su lectura. ¿Qué pensas?

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +  luego ejecútelo en JupyterHub
```suggestion
- Crea un Jupyter Notebook corto que incluya código Python y texto Markdown,
  luego ejecútalo en JupyterHub
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +- Lea la lección de shell de Software Carpentry
```suggestion
- Lee la lección de shell de Software Carpentry
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +¡así que el trabajo que haces ahora valdrá la pena más tarde!
```suggestion
Estas son tareas sugeridas de forma abierta: puedes hacer tanto como quieras;
no serás calificado o calificada. Lo importante es intentarlo.
Estas son herramientas que usaremos en todo CoCo,
¡así que el trabajo que haces ahora valdrá la pena más tarde!
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +Pérez cuando éramos estudiantes de posgrado en física en la Universidad de
```suggestion
Pérez cuando era estudiante de posgrado en física en la Universidad de
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +abierto e impulsada por la comunidad que supervisa el desarrollo de un
```suggestion
abierto e impulsada por la comunidad, que supervisa el desarrollo de un
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +En Coco, usaremos tres herramientas del ecosistema proyecto Jupyter:
```suggestion
En CoCo, usaremos tres herramientas del ecosistema Jupyter:
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +Un JupyterHub se puede instalar en la nube o localmente.
```suggestion
[JupyterHub](https://jupyter.org/hub) es un servicio que permite que
múltiples usuarios accedan a recursos computacionales, donde cada usuario
puede ejecutar Jupyter Notebook y otro software en su propio espacio de trabajo.
Un JupyterHub se puede instalar en la nube o localmente.
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +[JupyterHub][csdms-jhub] donde se pueden ejecutar los portátiles del programa CoCo.
```suggestion
[JupyterHub][csdms-jhub] donde se pueden ejecutar los Notebooks de CoCo.
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +JupyterLab es un entorno de desarrollo interactivo basado para el navegador.
```suggestion
JupyterLab es un entorno de desarrollo interactivo que se utiliza desde el navegador.
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +- aplicaciones de terminal, editor de texto y consola/terminales de código, y
```suggestion
- aplicaciones de terminal, editor de texto, y
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +JupyterLab es la interfaz de usuario predeterminada para JupyterHub.
```suggestion
JupyterLab es la interfaz predeterminada de JupyterHub.
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +Jupyter Notebook es un documento interactivo para escribir, explicar y ejecutar
```suggestion
Un Jupyter Notebook es un documento interactivo para escribir, explicar y ejecutar
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +En este momento, si aún no lo ha hecho, abra una terminal.
```suggestion
En este momento, si aún no lo has hecho, abre una terminal.
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +Cuando utiliza los comandos de shell en una terminal, puede realizar tareas
```suggestion
Cuando utilizas los comandos de shell en una terminal, puedes realizar tareas
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +Por analogía, piense en los atajos de teclado en su computadora:
```suggestion
Por analogía, piensa en los atajos de teclado en su computadora:
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +from texting shorthand: instead of brb or ttyl, it's `cd` or `rm`.
```suggestion
from texting shorthand: instead of brb or ttyl, it's `cd` (change directory) or `rm` (remove).
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +o tmb (también), es `cd` o `rm`.
```suggestion
o tmb (también), es `cd` (cambiar de directorio) o `rm` (remover).
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +Con un script, puede automatizar una tarea repetitiva.
```suggestion
Con un script, se puede automatizar una tarea repetitiva.
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +Los scripts son maravillosos para las canalizaciones de procesamiento de datos
```suggestion
Los scripts son maravillosos para construir flujos de procesamiento de datos
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +El prompt del sistema es donde ingresamos los comandos en una terminal.
```suggestion
El _prompt_ es donde ingresamos los comandos en una terminal.
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +El comando `ls` proporciona una lista de directorios.
```suggestion
El comando `ls` proporciona una lista de directorios y archivos.
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +para crear y almacenar información.
Corrijo aquí un término importante. El _home directory_ se traduce como _carpeta de usuario_. No es un directorio de inicio, sino un directorio que pertenece al usuario. Con pertenece me refiero literalmente: cada usuario es el owner de su carpeta de usuario.

```suggestion
Este directorio `/home/jupyter-mpiper` es especial. Éste es la
_carpeta de usuario_ para el usuario `jupyter-mpiper`.
Cada usuario tiene una _carpeta de usuario_ propia, que es la ubicación predeterminada
para crear y almacenar información.
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +que ejecuta Linux; el directorio de inicio en una máquina macOS o Windows será
```suggestion
que ejecuta Linux; la carpeta de usuario en una máquina macOS o Windows será
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +Este directorio de inicio contiene un conjunto de subdirectorios.
```suggestion
La carpeta de usuario contiene un conjunto de subdirectorios.
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +directorio de inicio.
```suggestion
Aunque hemos mirado en el directorio de archivos de muestra, permanecemos en la
carpeta de usuario.
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +Podemos indagar más; por ejemplo, para ver el contenido del directorio llamado data:
```suggestion
Podemos indagar más; por ejemplo, para ver el contenido del directorio llamado `data`:
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +También puede tomar sin argumentos:
```suggestion
También se puede usar sin argumentos:
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +Sin argumentos, `cd` siempre regresa a su directorio de inicio.
```suggestion
Sin argumentos, `cd` siempre regresa a su carpeta de usuario.
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +actual, mientras que dos puntos `..` son un atajo para el directorio principal:
Otro cambio importante aquí: el _parent directory_ es el directorio padre, no el directorio principal.
```suggestion
actual, mientras que dos puntos `..` son un atajo para el directorio-padre (_parent directory_):
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +Asimismo, la tilde `~` es un atajo para el directorio de inicio del usuario:
```suggestion
Asimismo, la tilde `~` es un atajo para la carpeta de usuario:
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +Desde su directorio de inicio, use el comando `mkdir` para crear un nuevo directorio:
```suggestion
Desde tu carpeta de usuario, usa el comando `mkdir` para crear un nuevo directorio:
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +Cambie al nuevo directorio y obtenga su contenido:
```suggestion
Cambia al nuevo directorio y obtén su contenido:
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +Tenga en cuenta que la copia y el original existen y son los mismos:
```suggestion
Tenga en cuenta que la copia y el original existen y tiene el mismo contenido:
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +Movamos **readme.md** hasta el directorio de inicio:
```suggestion
Movamos **readme.md** hasta la carpeta de usuario:
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +se ha movido al directorio de inicio.
```suggestion
se ha movido a la carpeta de usuario.
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +inicio son archivos diferentes!
```suggestion
¡También ten en cuenta que **README.md** y **readme.md** en la carpeta de
usuario son archivos diferentes!
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +Tenga en cuenta que el directorio **new** ahora está vacío porque **readme.md**
```suggestion
Ten en cuenta que el directorio **new** ahora está vacío porque **readme.md**
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +No existe el concepto de "papelera" o papelera de "reciclaje" en el shell.
```suggestion
No existe el concepto de "papelera" o "papelera de reciclaje" en el shell.
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +La siguiente tabla resume los comandos y caracteres especiales descrito en esta lección.
```suggestion
La siguiente tabla resume los comandos y caracteres especiales descritos en esta lección.
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +| /               | path delimiter / delimitado de dirección                                  |
```suggestion
| /               | path delimiter / delimitador de dirección                                 |
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +| ~               | home directory / directorio de inicio                                     |
```suggestion
| ~               | home directory / carpeta de usuario                                       |
```

2022-01-18 20:31 UTC, santisoler commented on coco_1_coding_environment.md
> +| -               | previous directory / un directorio arriba                                 |
```suggestion
| -               | previous directory / el directorio anterior                                 |
```

2022-01-18 21:10 UTC, mdpiper commented
@aguspesce Thank you very much for your work!

2022-01-18 21:38 UTC, aguspesce commented
@mdpiper, @isamarcortes and @santisoler... Are you ok with the idea to generate 2 files, one of the in English and other one in Spanish? 
If you are ok with this, the file name are  coco_1_coding_environment_español.md and coco_1_coding_environment_english.md

2022-01-18 21:56 UTC, mdpiper commented
I much prefer a single file, with interwoven English and Spanish text. As a novice Spanish speaker, I really enjoy seeing the versions side-by-side; it helps me understand how the ideas within individual sentences in English would be expressed in Spanish. I wouldn't get the same experience if I had to flip between files.

I think the side-by-side presentation in the notebooks for lessons 2-5 is a major strength, as well.

2022-01-18 22:00 UTC, mdpiper commented
Also (and this is more mundane), it would harder to keep the content in sync between two files.

2022-01-19 00:58 UTC, mdpiper commented
Let's open a separate issue to discuss one vs. two files further. I'd like it if we could merge this PR so we can use it in class tomorrow.

2022-01-19 14:29 UTC, merged